# Generated by Django 4.2.13 on 2026-06-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMERegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('personal_linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_number', models.CharField(max_length=10)),
                ('area_of_expertise', models.CharField(blank=True, max_length=100)),
                ('expertise_description', models.TextField(blank=True, max_length=1000)),
                ('cv_file', models.FileField(blank=True, help_text='Uploaded CV file', null=True, upload_to='cv_uploads/')),
                ('address_of_institute', models.TextField(max_length=500)),
                ('state_id', models.CharField(max_length=50)),
                ('district_id', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('import_source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('cv', 'CV Upload')], default='linkedin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SME Registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registration_id'], name='registratio_registr_756ea8_idx'), models.Index(fields=['email_id'], name='registratio_email_i_0ca466_idx'), models.Index(fields=['-created_at'], name='registratio_created_016f3c_idx')],
            },
        ),
    ]
