# Generated by Django 4.2.13 on 2026-06-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smeregistration',
            name='id',
        ),
        migrations.AlterField(
            model_name='smeregistration',
            name='registration_id',
            field=models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
